object DepVersion {
    const val buildGradleVersion = "7.0.3"
    const val firebaseCrashAnalyticGradleVersion = "2.7.1"
    const val googleServicesVersion =  "4.3.8"
    const val kotlinVersion = "1.6.0"

    const val appcompatVersion = "1.3.1"
    const val coreKtxVersion = "1.6.0"
    const val materialVersion = "1.4.0"
    const val recyclerViewVersion = "1.2.1"
    const val activityVersion = "1.4.0"
    const val fragmentVersion = "1.4.0"
    const val constraintLayoutVersion = "2.1.1"
    const val cardViewVersion = "1.0.0"
    const val lifecycleVersion = "2.4.0"
    const val preferenceVersion = "1.1.1"
    const val swipeLayoutVersion = "1.1.0"
    const val retrofitVersion = "2.9.0"
    const val hiltVersion = "2.39.1"
    const val picassoVersion = "2.71828"
    const val coilVersion = "1.4.0"
    const val timberVersion = "5.0.1"
    const val rxJava3Version = "3.1.2"
    const val rxAndroid3Version = "3.0.0"
    const val okhttp3Version = "4.9.0"
    const val gsonVersion = "2.8.8"
    const val sdpVersion = "1.0.6"
    const val roomVersion = "2.3.0"
    const val mapVersion = "17.0.1"
    const val mapLocationVersion = "18.0.0"
    const val mapPlaceVersion = "2.4.0"
    const val firebaseBomVersion= "28.2.1"
    const val circleImageViewVersion = "3.1.0"
    const val navigationVersion = "2.4.2"
    const val navigationSafeArgsVersion = "2.3.5"
    const val coroutinesVersion = "1.5.1"
    const val leakcanaryVersion = "2.7"
    const val playCoreVersion = "1.10.2"
    const val playCoreKtxVersion = "1.8.1"
    const val facebookVersion = "12.0.1"
    const val facebookMarketingVersion = "7.0.1"
    const val viewPagerDotIndicatorVersion = "4.2"

    const val espressoVersion = "3.4.0"
    const val junitVersion = "4.13.2"
    const val junitExtVersion = "1.1.3"


    const val imageZoom = "2.3.0"

    const val composeActivity = "1.4.0"

    const val composeMaterial = "1.1.1"
    const val composeAnimation = "1.1.1"
    const val composeUiTooling = "1.1.1"
    const val compose = "1.1.1"
    const val composeViewModel = "2.4.1"


}